#! /usr/bin/env bash
cd "$(dirname $0)"
if [ -t 1 ] ;
then
    java -jar youtube-video-list-0.1.0-SNAPSHOT-standalone.jar -o tsv $1
else
    java -jar youtube-video-list-0.1.0-SNAPSHOT-standalone.jar $1
fi




